@startuml
title 次期LMS 系统构成图

package "次期LMS 系统" {
    [ログインスタブ画面] --> [学習者用研修検索TOP画面]
    [学習者用研修検索TOP画面] --> [中分類紹介画面]
    [学習者用研修検索TOP画面] --> [検索一覧画面]
    [検索一覧画面] --> [詳細・募集一覧画面]
    [検索一覧画面] --> [要検討リスト画面]
}

@enduml