@startuml 管理者用例图_第1组

' 定义角色
left to right direction
actor "管理者" as Manager

' 定义用例
rectangle "酒店IOT管理系统" {
  usecase "用户login" as UC1
  usecase "查看登录用户信息" as UC2
  usecase "修改密码" as UC3
  usecase "logout" as UC4
  usecase "用户管理" as UC5 #yellow
  usecase "菜单管理" as UC51 #yellow
}

' 建立关系
Manager --> UC1
Manager --> UC2
Manager --> UC3
Manager --> UC4
Manager --> UC5
Manager --> UC51

@enduml